name: deploy-to-production
on:
  # release:
  #   types: [published]
  push:
    branches:
      - release/haryana-skills
jobs:
  deploy-to-production:
    environment: release-haryana-skills
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "placeholder-text"

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files with rsync
        run: rsync -avz --exclude '.git' --exclude '.github' . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/x-admin/

      - name: Rebuild containers with docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/x-admin/
            export FUSIONAUTH_DOMAIN=${{secrets.FUSIONAUTH_DOMAIN}} &&
            export FUSIONAUTH_API_KEY=${{secrets.FUSIONAUTH_API_KEY}} &&
            export HASURA_URL=${{secrets.HASURA_URL}} &&
            export HASURA_ADMIN_SECRET=${{secrets.HASURA_ADMIN_SECRET}} &&
            export NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}
            docker-compose up -d --build
